### ISSUE TITLE
Refactor Codebase to support WASM

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-rust-workspace#20]
- [ ] Identify functionalities impacted
- [ ] Implement structure for sending a transaction
- [ ] Implement structure for receiving a transaction
- [ ] Implement structure for sending a message and wait for reply
- [ ] Create Unit test & test
- [ ] Update design
- [ ] Refactor Code base
- [ ] Update Unit test and conduct tests

**Comment by SankaD** [comment]
Will be handled in #281
