### ISSUE TITLE
Load WASM library into a saito-web with test setup

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-rust-workspace#21]
- [x] Implement basic structure
- [x] Setup saito-js with webpack
- [x] Loading wasm inside the web browser
- [x] Loading wasm functionality inside the node js server
- [x] Setting up mocha testing for saito-js library

**Comment by SankaD** [comment]
Code can be compiled into WASM with webpack. But generates 2 files 1 js and 1 wasm. This need to be fixed for the AppStore functionality. Or the AppStore functionality needs to be changed to work with a tar file or multiple files.
