### ISSUE TITLE
run instructions

### ISSUE THREAD

**Issue by benjyz** [SaitoTech/saito-rust-workspace#276]
in saito-rust I do cargo run and get

```
Running saito
2023-01-04T10:02:34.075427Z ERROR saito_rust::saito::config_handler: Error { tag: Tag::Default, profile: Some(Profile(Uncased { string: "default" })), metadata: None, path: [], kind: MissingField("server"), prev: None }
2023-01-04T10:02:34.075635Z ERROR saito_rust: panic occurred in file 'saito-rust/src/main.rs' at line 551, exiting ..
thread 'main' panicked at 'loading configs failed: Kind(InvalidInput)', saito-rust/src/main.rs:551:18
```

seems like a config file is missing. some info in readme would be helpful

**Comment by SankaD** [comment]
Check with this file

```
{
  "server": {
    "host": "127.0.0.1",
    "port": 12101,
    "protocol": "http",
    "endpoint": {
      "host": "127.0.0.1",
      "port": 12101,
      "protocol": "http"
    },
    "verification_threads": 4,
    "channel_size": 1000,
    "stat_timer_in_ms": 5000,
    "thread_sleep_time_in_ms": 10,
    "block_fetch_batch_size": 10
  },
  "peers": [
   
  ]
}

```

**Comment by benjyz** [comment]
thanks, I put this in configs/config.json and then I get

`2023-01-04T14:14:55.240450Z ERROR saito_core::core::data::storage: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

**Comment by SankaD** [comment]
If there's no peers, it starts from beginning with genesis block. you can run 2 nodes where one has peer as the other to connect 2 nodes

**Comment by benjyz** [comment]
@SankaD would like to add markdown for step-by-step instructions. the most convenient to start 2 nodes is to be able to pass config as command line arguments ```runnode -config config1.json```, which then can point to different storage file etc.
