### ISSUE TITLE
Implement a simple node using basic wasm interface

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-rust-workspace#280]

**Comment by benjyz** [comment]
I could try and help with this issue. I want to create a simple node which pulls the chat

**Comment by SankaD** [comment]
This is a bit more complex though. Need to convert the total rust code base into WASM (currently working) and use that to run a simple node (which I'm doing currently). After this is done and #282 also you will be able to implement things on your end.

**Comment by SankaD** [comment]
Implemented test node is at https://github.com/SaitoTech/saito-wasm-web-test.

(Have to use npm link saito-wasm to link the libs till the package is published to npmjs)
