### ISSUE TITLE
Create tool to dump UTXO , metadata to a file

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-rust-workspace#390]
in order to observe balances and check them need to check the current state of the chain in in particular utxoset, blocks, BlockRing.

1) generate a summary given current state in a pretty printed string format.
2) write to file.

**Comment by benjiqq** [comment]
David Lancashire, [9 Jun BE 2566 15:00:29]:
...1. extract publickey
2. extract amount

check if the amount is over an arbitrary threshold

please print to file in a format similar to the issuance files

publickey \t amount \t type (normal)

we only want to do this for entries in the hashmap that are spendable (i.e. key => value (1) )

**Comment by benjiqq** [comment]
proposed next steps
* more advanced testing of different transactions
