### ISSUE TITLE
Change balance limit in issuance mode from preserving balances >25,000 to >=25,000 (it is deleting 25k balances...

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-rust-workspace#540]

**Comment by arpee** [comment]
I have just tested this and balances of exactly 25000 are being preserved now.

BUT the sub 25,000 balances are not being swept up into the project wallet...

Has that work been finished (i know it was in a PR), and do I have the most recent binary? I got it from the newest build&publish job i could find...

**Comment by umairkhannn** [comment]
Sharing my findings during testing testing here...

**Comment by umairkhannn** [comment]
**CASE 1: Send Balance greater than 25,000 SAITO**

**Wallet 1:**
Initial balance: 140000 SAITO
Public key: qxjf4BC2556utVHv2X2uMinHSUyBRCPfRFkTNQdq6Z7j


![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/440c82a3-90bd-42a3-b2de-a489e242afc3)



**Wallet 2:**
Initial balance: 0 SAITO
Public key: qqbtLqinhD36YRG9j7q6po9BAeNn9YV2rAsuHVs7SiYd

![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/bee02831-c560-466c-bb3e-5f89cf594bd7)

**Project key:**
Initial balance: 10000000 SAITO
Public key: q6TTBeSStCLXEPoS5TUVAxNiGGnRDZQenpvAXXAfTmtA


Steps:
- Sending 30000 SAITO from WALLET 1 to WALLET 2
- `./saito-rust --mode utxo-issuance` running with cron job creating issuance file in background.


**Result:** 
**_Balance sent from wallet 1 to wallet 2 without issue and balance also updated in issuance file:_**


Project key (balance unchanged)
10000000	q6TTBeSStCLXEPoS5TUVAxNiGGnRDZQenpvAXXAfTmtA	Normal

Wallet 1
110000	qxjf4BC2556utVHv2X2uMinHSUyBRCPfRFkTNQdq6Z7j	Normal

Wallet 2
30000	qqbtLqinhD36YRG9j7q6po9BAeNn9YV2rAsuHVs7SiYd	Normal

**Comment by umairkhannn** [comment]
**CASE 2: Send Balance less than 25,000 SAITO**

**Wallet 1:**
Initial balance: 110,000 SAITO
Public key: qxjf4BC2556utVHv2X2uMinHSUyBRCPfRFkTNQdq6Z7j



![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/8d418743-8887-4db0-98cc-34ee7fbac398)




**Wallet 2:**
Initial balance: 0 SAITO
Public key: uFzdFMQMgCgL9wH6yhUESteB2jat5arZ7QSsJeuswQhN



![Image](https://github.com/SaitoTech/saito-lite-rust/assets/104337801/c57ba327-86f5-4801-8b22-5c5cefe97773)


**Project key:**
Initial balance: 10,000,000 SAITO
Public key: q6TTBeSStCLXEPoS5TUVAxNiGGnRDZQenpvAXXAfTmtA


Steps:
- Sending 10000 SAITO from WALLET 1 to WALLET 2
- `./saito-rust --mode utxo-issuance` running with cron job creating issuance file in background.


**Result:** 
**_Balance sent from wallet 1 to wallet 2 and balance also updated in issuance file:_**

**Issue:**
**Dust balance 10000 SAITO isnt being added to the project key.**


**Issuance file balances after transfer:**
Project key (balance unchanged)
10,000,000	q6TTBeSStCLXEPoS5TUVAxNiGGnRDZQenpvAXXAfTmtA	Normal

Wallet 1
100,000	qxjf4BC2556utVHv2X2uMinHSUyBRCPfRFkTNQdq6Z7j	Normal

Wallet 2
10,000	qqbtLqinhD36YRG9j7q6po9BAeNn9YV2rAsuHVs7SiYd	Normal

**Comment by umairkhannn** [comment]
After latest push from @davikstone2 i tested it again and confirmed that dust balance is being added to project key on creation of new issuance file. 

@SankaD @arpee
