### ISSUE TITLE
Remove extra quotes from 'block id' in block json.

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-rust-workspace#560]
![Image](https://user-images.githubusercontent.com/2867779/269290577-af205807-ff88-401d-a88e-08ae0ecb696a.png)

Block id is stored with extra quotes in block json...

These quotes should be removed.

**Comment by SankaD** [comment]
![Image](https://github.com/SaitoTech/saito-rust-workspace/assets/2997480/e6019da2-d695-4393-a227-4e488f7bb79d)

this is still not fixed BTW
