### ISSUE TITLE
Implement Rate Limiting to Prevent DDoS Attacks in P2P Network (WASM)

### ISSUE THREAD

**Issue by davikstone2** [SaitoTech/saito-rust-workspace#767]
The peer-to-peer (P2P) network is currently vulnerable to  DDoS attacks. To enhance the security and stability of the network, we need to implement rate limiting across various interaction points. This issue outlines the need for and steps to integrate rate limiting into the P2P network, specifically targeting the areas most susceptible to DDoS attacks.

- Implement rate limiting to prevent connection flooding and repeated handshake attempts from overwhelming nodes.

**Comment by SankaD** [comment]
- [ ] Rate limit for Handshakes
- [ ] Rate limit for received messages
- [ ] Checks for peers sending invalid blocks (blacklisting,etc..)
- [ ] Checks for peers producing multiple blocks t the same depth
- [ ] Blacklist peers if they create invalid blocks
- [ ] Checks for peers sending blocks too far in the chain/forks
